### ISSUE TITLE
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

### ISSUE THREAD

**Issue by KevinYang0120** [chenzitw/semantic-validator#7]
I got this warnings in frontend
![image](https://user-images.githubusercontent.com/30248187/60633248-5a328f00-9e3c-11e9-8938-3bc7e34c3c0f.png)

**Comment by chenzitw** [comment]
Hi, thank you for the issue report. The issue has been fixed in #8 . Please use the new version 0.1.1 and try again.
The reason for causing this problem is that I chose to compile to UMD module by TypeScript compiler. I thought the UMD module is compatible with both CommonJS and AMD module system. But it causes we need the `umd-compat-loader` for Webpack to import correctly.
Consider that the CommonJS module system is widely used in NPM ecosystem. I just changed the config to compile to CommonJS module.
